export const AUTH_LOGOUT="AUTH_LOGOUT";
export const REQUEST_ERROR="REQUEST_ERROR";
export const REQUEST_START="REQUEST_START";
export const REQUEST_SUCCESS="REQUEST_SUCCESS";
export const GET_CATEGORY_LIST="GET_CATEGORY_LIST";
export const GET_MAKER_LIST="GET_MAKER_LIST";
